<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Materia', 'doctrine');

/**
 * BaseMateria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_materia
 * @property string $nombre
 * @property integer $cantidad_unidades
 * @property Doctrine_Collection $ProfesorMateria
 * 
 * @method integer             getIdMateria()         Returns the current record's "id_materia" value
 * @method string              getNombre()            Returns the current record's "nombre" value
 * @method integer             getCantidadUnidades()  Returns the current record's "cantidad_unidades" value
 * @method Doctrine_Collection getProfesorMateria()   Returns the current record's "ProfesorMateria" collection
 * @method Materia             setIdMateria()         Sets the current record's "id_materia" value
 * @method Materia             setNombre()            Sets the current record's "nombre" value
 * @method Materia             setCantidadUnidades()  Sets the current record's "cantidad_unidades" value
 * @method Materia             setProfesorMateria()   Sets the current record's "ProfesorMateria" collection
 * 
 * @package    escuela
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMateria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('materia');
        $this->hasColumn('id_materia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 70, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 70,
             ));
        $this->hasColumn('cantidad_unidades', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProfesorMateria', array(
             'local' => 'id_materia',
             'foreign' => 'materiaid_materia'));
    }
}