<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Profesor', 'doctrine');

/**
 * BaseProfesor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_profesor
 * @property string $nombre
 * @property string $ap_paterno
 * @property string $ap_materno
 * @property Doctrine_Collection $ProfesorMateria
 * 
 * @method integer             getIdProfesor()      Returns the current record's "id_profesor" value
 * @method string              getNombre()          Returns the current record's "nombre" value
 * @method string              getApPaterno()       Returns the current record's "ap_paterno" value
 * @method string              getApMaterno()       Returns the current record's "ap_materno" value
 * @method Doctrine_Collection getProfesorMateria() Returns the current record's "ProfesorMateria" collection
 * @method Profesor            setIdProfesor()      Sets the current record's "id_profesor" value
 * @method Profesor            setNombre()          Sets the current record's "nombre" value
 * @method Profesor            setApPaterno()       Sets the current record's "ap_paterno" value
 * @method Profesor            setApMaterno()       Sets the current record's "ap_materno" value
 * @method Profesor            setProfesorMateria() Sets the current record's "ProfesorMateria" collection
 * 
 * @package    escuela
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfesor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profesor');
        $this->hasColumn('id_profesor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('ap_paterno', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('ap_materno', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProfesorMateria', array(
             'local' => 'id_profesor',
             'foreign' => 'profesorid_profesor'));
    }
}