<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Alumno', 'doctrine');

/**
 * BaseAlumno
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_alumno
 * @property integer $nombre
 * @property string $ap_paterno
 * @property string $ap_materno
 * @property integer $n_lista
 * @property integer $id_grupo
 * @property Grupo $Grupo
 * @property Doctrine_Collection $AlumnoProfesorMateria
 * 
 * @method integer             getIdAlumno()              Returns the current record's "id_alumno" value
 * @method integer             getNombre()                Returns the current record's "nombre" value
 * @method string              getApPaterno()             Returns the current record's "ap_paterno" value
 * @method string              getApMaterno()             Returns the current record's "ap_materno" value
 * @method integer             getNLista()                Returns the current record's "n_lista" value
 * @method integer             getIdGrupo()               Returns the current record's "id_grupo" value
 * @method Grupo               getGrupo()                 Returns the current record's "Grupo" value
 * @method Doctrine_Collection getAlumnoProfesorMateria() Returns the current record's "AlumnoProfesorMateria" collection
 * @method Alumno              setIdAlumno()              Sets the current record's "id_alumno" value
 * @method Alumno              setNombre()                Sets the current record's "nombre" value
 * @method Alumno              setApPaterno()             Sets the current record's "ap_paterno" value
 * @method Alumno              setApMaterno()             Sets the current record's "ap_materno" value
 * @method Alumno              setNLista()                Sets the current record's "n_lista" value
 * @method Alumno              setIdGrupo()               Sets the current record's "id_grupo" value
 * @method Alumno              setGrupo()                 Sets the current record's "Grupo" value
 * @method Alumno              setAlumnoProfesorMateria() Sets the current record's "AlumnoProfesorMateria" collection
 * 
 * @package    escuela
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlumno extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('alumno');
        $this->hasColumn('id_alumno', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ap_paterno', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('ap_materno', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('n_lista', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_grupo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Grupo', array(
             'local' => 'id_grupo',
             'foreign' => 'id_grupo'));

        $this->hasMany('AlumnoProfesorMateria', array(
             'local' => 'id_alumno',
             'foreign' => 'alumnoid_alumno'));
    }
}