<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Grupo', 'doctrine');

/**
 * BaseGrupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_grupo
 * @property Doctrine_Collection $Alumno
 * 
 * @method integer             getIdGrupo()  Returns the current record's "id_grupo" value
 * @method Doctrine_Collection getAlumno()   Returns the current record's "Alumno" collection
 * @method Grupo               setIdGrupo()  Sets the current record's "id_grupo" value
 * @method Grupo               setAlumno()   Sets the current record's "Alumno" collection
 * 
 * @package    escuela
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGrupo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grupo');
        $this->hasColumn('id_grupo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Alumno', array(
             'local' => 'id_grupo',
             'foreign' => 'id_grupo'));
    }
}