<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Grupo', 'doctrine');

/**
 * BaseGrupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_grupo
 * @property integer $semestre
 * @property integer $num_grupo
 * @property Doctrine_Collection $Alumno
 * @property Doctrine_Collection $ProfesorMateria
 * 
 * @method integer             getIdGrupo()         Returns the current record's "id_grupo" value
 * @method integer             getSemestre()        Returns the current record's "semestre" value
 * @method integer             getNumGrupo()        Returns the current record's "num_grupo" value
 * @method Doctrine_Collection getAlumno()          Returns the current record's "Alumno" collection
 * @method Doctrine_Collection getProfesorMateria() Returns the current record's "ProfesorMateria" collection
 * @method Grupo               setIdGrupo()         Sets the current record's "id_grupo" value
 * @method Grupo               setSemestre()        Sets the current record's "semestre" value
 * @method Grupo               setNumGrupo()        Sets the current record's "num_grupo" value
 * @method Grupo               setAlumno()          Sets the current record's "Alumno" collection
 * @method Grupo               setProfesorMateria() Sets the current record's "ProfesorMateria" collection
 * 
 * @package    escuela
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGrupo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grupo');
        $this->hasColumn('id_grupo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('semestre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('num_grupo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Alumno', array(
             'local' => 'id_grupo',
             'foreign' => 'id_grupo'));

        $this->hasMany('ProfesorMateria', array(
             'local' => 'id_grupo',
             'foreign' => 'grupoid_grupo'));
    }
}