<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RegTareasNoRealizadas', 'doctrine');

/**
 * BaseRegTareasNoRealizadas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $fecha
 * @property string $descripcion
 * @property integer $num_unidad
 * @property integer $alumno_profesor_materiaid_alumno_profesor_materia
 * @property AlumnoProfesorMateria $AlumnoProfesorMateria
 * 
 * @method integer               getId()                                                Returns the current record's "id" value
 * @method date                  getFecha()                                             Returns the current record's "fecha" value
 * @method string                getDescripcion()                                       Returns the current record's "descripcion" value
 * @method integer               getNumUnidad()                                         Returns the current record's "num_unidad" value
 * @method integer               getAlumnoProfesorMateriaidAlumnoProfesorMateria()      Returns the current record's "alumno_profesor_materiaid_alumno_profesor_materia" value
 * @method AlumnoProfesorMateria getAlumnoProfesorMateria()                             Returns the current record's "AlumnoProfesorMateria" value
 * @method RegTareasNoRealizadas setId()                                                Sets the current record's "id" value
 * @method RegTareasNoRealizadas setFecha()                                             Sets the current record's "fecha" value
 * @method RegTareasNoRealizadas setDescripcion()                                       Sets the current record's "descripcion" value
 * @method RegTareasNoRealizadas setNumUnidad()                                         Sets the current record's "num_unidad" value
 * @method RegTareasNoRealizadas setAlumnoProfesorMateriaidAlumnoProfesorMateria()      Sets the current record's "alumno_profesor_materiaid_alumno_profesor_materia" value
 * @method RegTareasNoRealizadas setAlumnoProfesorMateria()                             Sets the current record's "AlumnoProfesorMateria" value
 * 
 * @package    escuela
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegTareasNoRealizadas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reg_tareas_no_realizadas');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('num_unidad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('alumno_profesor_materiaid_alumno_profesor_materia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AlumnoProfesorMateria', array(
             'local' => 'alumno_profesor_materiaid_alumno_profesor_materia',
             'foreign' => 'id_alumno_profesor_materia'));
    }
}