<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Materia', 'doctrine');

/**
 * BaseMateria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $clave
 * @property string $nombre
 * @property integer $semestre
 * @property Doctrine_Collection $ProfesorMateria
 * 
 * @method string              getClave()           Returns the current record's "clave" value
 * @method string              getNombre()          Returns the current record's "nombre" value
 * @method integer             getSemestre()        Returns the current record's "semestre" value
 * @method Doctrine_Collection getProfesorMateria() Returns the current record's "ProfesorMateria" collection
 * @method Materia             setClave()           Sets the current record's "clave" value
 * @method Materia             setNombre()          Sets the current record's "nombre" value
 * @method Materia             setSemestre()        Sets the current record's "semestre" value
 * @method Materia             setProfesorMateria() Sets the current record's "ProfesorMateria" collection
 * 
 * @package    escuela
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMateria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('materia');
        $this->hasColumn('clave', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('nombre', 'string', 70, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 70,
             ));
        $this->hasColumn('semestre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProfesorMateria', array(
             'local' => 'clave',
             'foreign' => 'materiaclave'));
    }
}