<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Localidad', 'doctrine');

/**
 * BaseLocalidad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $clave_localidad
 * @property string $nombre
 * @property integer $clave_municipio
 * @property Municipios $Municipios
 * @property Doctrine_Collection $Tutor
 * 
 * @method integer             getClaveLocalidad()  Returns the current record's "clave_localidad" value
 * @method string              getNombre()          Returns the current record's "nombre" value
 * @method integer             getClaveMunicipio()  Returns the current record's "clave_municipio" value
 * @method Municipios          getMunicipios()      Returns the current record's "Municipios" value
 * @method Doctrine_Collection getTutor()           Returns the current record's "Tutor" collection
 * @method Localidad           setClaveLocalidad()  Sets the current record's "clave_localidad" value
 * @method Localidad           setNombre()          Sets the current record's "nombre" value
 * @method Localidad           setClaveMunicipio()  Sets the current record's "clave_municipio" value
 * @method Localidad           setMunicipios()      Sets the current record's "Municipios" value
 * @method Localidad           setTutor()           Sets the current record's "Tutor" collection
 * 
 * @package    escuela
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLocalidad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('localidad');
        $this->hasColumn('clave_localidad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 80,
             ));
        $this->hasColumn('clave_municipio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Municipios', array(
             'local' => 'clave_municipio',
             'foreign' => 'clave_municipio'));

        $this->hasMany('Tutor', array(
             'local' => 'clave_localidad',
             'foreign' => 'clave_localidad'));
    }
}