<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RegFaltas', 'doctrine');

/**
 * BaseRegFaltas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $fecha
 * @property integer $num_unidad
 * @property integer $id_alumno_profesor_materia
 * @property AlumnoProfesorMateria $AlumnoProfesorMateria
 * 
 * @method integer               getId()                         Returns the current record's "id" value
 * @method date                  getFecha()                      Returns the current record's "fecha" value
 * @method integer               getNumUnidad()                  Returns the current record's "num_unidad" value
 * @method integer               getIdAlumnoProfesorMateria()    Returns the current record's "id_alumno_profesor_materia" value
 * @method AlumnoProfesorMateria getAlumnoProfesorMateria()      Returns the current record's "AlumnoProfesorMateria" value
 * @method RegFaltas             setId()                         Sets the current record's "id" value
 * @method RegFaltas             setFecha()                      Sets the current record's "fecha" value
 * @method RegFaltas             setNumUnidad()                  Sets the current record's "num_unidad" value
 * @method RegFaltas             setIdAlumnoProfesorMateria()    Sets the current record's "id_alumno_profesor_materia" value
 * @method RegFaltas             setAlumnoProfesorMateria()      Sets the current record's "AlumnoProfesorMateria" value
 * 
 * @package    escuela
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegFaltas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reg_faltas');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('num_unidad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_alumno_profesor_materia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AlumnoProfesorMateria', array(
             'local' => 'id_alumno_profesor_materia',
             'foreign' => 'id_alumno_profesor_materia'));
    }
}