<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/09/24 19:36:16

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=escuela',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
