<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/09/10 21:35:41

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=escuela',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
