<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/09/11 23:42:07
sfConfig::add(array(
  'mod_registrodiario_enabled' => true,
  'mod_registrodiario_view_class' => 'sfPHP',
));
