<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/09/12 14:06:50
sfConfig::add(array(
  'mod_registrodiario_enabled' => true,
  'mod_registrodiario_view_class' => 'sfPHP',
));
