<?php

/**
 * Grupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    escuela
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Grupo extends BaseGrupo
{
    public function __toString() {
        return ($this->getSemestre()*100)+$this->getNumGrupo();
    }

}