<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProfesorMateria', 'doctrine');

/**
 * BaseProfesorMateria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_profesor_materia
 * @property string $periodo
 * @property integer $profesorid_profesor
 * @property string $materiaclave
 * @property integer $grupoid_grupo
 * @property Grupo $Grupo
 * @property Materia $Materia
 * @property Profesor $Profesor
 * @property Doctrine_Collection $AlumnoProfesorMateria
 * 
 * @method integer             getIdProfesorMateria()     Returns the current record's "id_profesor_materia" value
 * @method string              getPeriodo()               Returns the current record's "periodo" value
 * @method integer             getProfesoridProfesor()    Returns the current record's "profesorid_profesor" value
 * @method string              getMateriaclave()          Returns the current record's "materiaclave" value
 * @method integer             getGrupoidGrupo()          Returns the current record's "grupoid_grupo" value
 * @method Grupo               getGrupo()                 Returns the current record's "Grupo" value
 * @method Materia             getMateria()               Returns the current record's "Materia" value
 * @method Profesor            getProfesor()              Returns the current record's "Profesor" value
 * @method Doctrine_Collection getAlumnoProfesorMateria() Returns the current record's "AlumnoProfesorMateria" collection
 * @method ProfesorMateria     setIdProfesorMateria()     Sets the current record's "id_profesor_materia" value
 * @method ProfesorMateria     setPeriodo()               Sets the current record's "periodo" value
 * @method ProfesorMateria     setProfesoridProfesor()    Sets the current record's "profesorid_profesor" value
 * @method ProfesorMateria     setMateriaclave()          Sets the current record's "materiaclave" value
 * @method ProfesorMateria     setGrupoidGrupo()          Sets the current record's "grupoid_grupo" value
 * @method ProfesorMateria     setGrupo()                 Sets the current record's "Grupo" value
 * @method ProfesorMateria     setMateria()               Sets the current record's "Materia" value
 * @method ProfesorMateria     setProfesor()              Sets the current record's "Profesor" value
 * @method ProfesorMateria     setAlumnoProfesorMateria() Sets the current record's "AlumnoProfesorMateria" collection
 * 
 * @package    escuela
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfesorMateria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profesor_materia');
        $this->hasColumn('id_profesor_materia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('periodo', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('profesorid_profesor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('materiaclave', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('grupoid_grupo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Grupo', array(
             'local' => 'grupoid_grupo',
             'foreign' => 'id_grupo'));

        $this->hasOne('Materia', array(
             'local' => 'materiaclave',
             'foreign' => 'clave'));

        $this->hasOne('Profesor', array(
             'local' => 'profesorid_profesor',
             'foreign' => 'id_profesor'));

        $this->hasMany('AlumnoProfesorMateria', array(
             'local' => 'id_profesor_materia',
             'foreign' => 'profesor_materiaid_profesor_materia'));
    }
}