<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VariablesGlobales', 'doctrine');

/**
 * BaseVariablesGlobales
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_variables_globales
 * @property date $eval_fecha_inicio
 * @property date $eval_fecha_fin
 * @property integer $estatus
 * @property integer $unidad_actual
 * @property string $semestre_actual
 * 
 * @method integer           getIdVariablesGlobales()   Returns the current record's "id_variables_globales" value
 * @method date              getEvalFechaInicio()       Returns the current record's "eval_fecha_inicio" value
 * @method date              getEvalFechaFin()          Returns the current record's "eval_fecha_fin" value
 * @method integer           getEstatus()               Returns the current record's "estatus" value
 * @method integer           getUnidadActual()          Returns the current record's "unidad_actual" value
 * @method string            getSemestreActual()        Returns the current record's "semestre_actual" value
 * @method VariablesGlobales setIdVariablesGlobales()   Sets the current record's "id_variables_globales" value
 * @method VariablesGlobales setEvalFechaInicio()       Sets the current record's "eval_fecha_inicio" value
 * @method VariablesGlobales setEvalFechaFin()          Sets the current record's "eval_fecha_fin" value
 * @method VariablesGlobales setEstatus()               Sets the current record's "estatus" value
 * @method VariablesGlobales setUnidadActual()          Sets the current record's "unidad_actual" value
 * @method VariablesGlobales setSemestreActual()        Sets the current record's "semestre_actual" value
 * 
 * @package    escuela
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVariablesGlobales extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('variables_globales');
        $this->hasColumn('id_variables_globales', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('eval_fecha_inicio', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('eval_fecha_fin', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('estatus', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('unidad_actual', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('semestre_actual', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}