<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProfesorMateria', 'doctrine');

/**
 * BaseProfesorMateria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_profesor_materia
 * @property integer $materiaid_materia
 * @property integer $profesorid_profesor
 * @property integer $anio
 * @property integer $semestreid_semestre
 * @property Semestre $Semestre
 * @property Materia $Materia
 * @property Profesor $Profesor
 * @property Doctrine_Collection $AlumnoProfesorMateria
 * 
 * @method integer             getIdProfesorMateria()     Returns the current record's "id_profesor_materia" value
 * @method integer             getMateriaidMateria()      Returns the current record's "materiaid_materia" value
 * @method integer             getProfesoridProfesor()    Returns the current record's "profesorid_profesor" value
 * @method integer             getAnio()                  Returns the current record's "anio" value
 * @method integer             getSemestreidSemestre()    Returns the current record's "semestreid_semestre" value
 * @method Semestre            getSemestre()              Returns the current record's "Semestre" value
 * @method Materia             getMateria()               Returns the current record's "Materia" value
 * @method Profesor            getProfesor()              Returns the current record's "Profesor" value
 * @method Doctrine_Collection getAlumnoProfesorMateria() Returns the current record's "AlumnoProfesorMateria" collection
 * @method ProfesorMateria     setIdProfesorMateria()     Sets the current record's "id_profesor_materia" value
 * @method ProfesorMateria     setMateriaidMateria()      Sets the current record's "materiaid_materia" value
 * @method ProfesorMateria     setProfesoridProfesor()    Sets the current record's "profesorid_profesor" value
 * @method ProfesorMateria     setAnio()                  Sets the current record's "anio" value
 * @method ProfesorMateria     setSemestreidSemestre()    Sets the current record's "semestreid_semestre" value
 * @method ProfesorMateria     setSemestre()              Sets the current record's "Semestre" value
 * @method ProfesorMateria     setMateria()               Sets the current record's "Materia" value
 * @method ProfesorMateria     setProfesor()              Sets the current record's "Profesor" value
 * @method ProfesorMateria     setAlumnoProfesorMateria() Sets the current record's "AlumnoProfesorMateria" collection
 * 
 * @package    escuela
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfesorMateria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profesor_materia');
        $this->hasColumn('id_profesor_materia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('materiaid_materia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('profesorid_profesor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('anio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('semestreid_semestre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Semestre', array(
             'local' => 'semestreid_semestre',
             'foreign' => 'id_semestre'));

        $this->hasOne('Materia', array(
             'local' => 'materiaid_materia',
             'foreign' => 'id_materia'));

        $this->hasOne('Profesor', array(
             'local' => 'profesorid_profesor',
             'foreign' => 'id_profesor'));

        $this->hasMany('AlumnoProfesorMateria', array(
             'local' => 'id_profesor_materia',
             'foreign' => 'profesor_materiaid_profesor_materia'));
    }
}