<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Municipios', 'doctrine');

/**
 * BaseMunicipios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $clave_municipio
 * @property string $nombre
 * @property Doctrine_Collection $Localidad
 * @property Doctrine_Collection $Tutor
 * 
 * @method integer             getClaveMunicipio()  Returns the current record's "clave_municipio" value
 * @method string              getNombre()          Returns the current record's "nombre" value
 * @method Doctrine_Collection getLocalidad()       Returns the current record's "Localidad" collection
 * @method Doctrine_Collection getTutor()           Returns the current record's "Tutor" collection
 * @method Municipios          setClaveMunicipio()  Sets the current record's "clave_municipio" value
 * @method Municipios          setNombre()          Sets the current record's "nombre" value
 * @method Municipios          setLocalidad()       Sets the current record's "Localidad" collection
 * @method Municipios          setTutor()           Sets the current record's "Tutor" collection
 * 
 * @package    escuela
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMunicipios extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('municipios');
        $this->hasColumn('clave_municipio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 80,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Localidad', array(
             'local' => 'clave_municipio',
             'foreign' => 'clave_municipio'));

        $this->hasMany('Tutor', array(
             'local' => 'clave_municipio',
             'foreign' => 'clave_municipio'));
    }
}