<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Rol', 'doctrine');

/**
 * BaseRol
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_rol
 * @property string $nombre
 * @property Doctrine_Collection $Cuenta
 * 
 * @method integer             getIdRol()  Returns the current record's "id_rol" value
 * @method string              getNombre() Returns the current record's "nombre" value
 * @method Doctrine_Collection getCuenta() Returns the current record's "Cuenta" collection
 * @method Rol                 setIdRol()  Sets the current record's "id_rol" value
 * @method Rol                 setNombre() Sets the current record's "nombre" value
 * @method Rol                 setCuenta() Sets the current record's "Cuenta" collection
 * 
 * @package    escuela
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRol extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rol');
        $this->hasColumn('id_rol', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Cuenta', array(
             'local' => 'id_rol',
             'foreign' => 'rolid_rol'));
    }
}