<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PaseDeLista', 'doctrine');

/**
 * BasePaseDeLista
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_pase_de_lista
 * @property date $fecha
 * @property integer $id_profesor_materia
 * @property ProfesorMateria $ProfesorMateria
 * 
 * @method integer         getIdPaseDeLista()       Returns the current record's "id_pase_de_lista" value
 * @method date            getFecha()               Returns the current record's "fecha" value
 * @method integer         getIdProfesorMateria()   Returns the current record's "id_profesor_materia" value
 * @method ProfesorMateria getProfesorMateria()     Returns the current record's "ProfesorMateria" value
 * @method PaseDeLista     setIdPaseDeLista()       Sets the current record's "id_pase_de_lista" value
 * @method PaseDeLista     setFecha()               Sets the current record's "fecha" value
 * @method PaseDeLista     setIdProfesorMateria()   Sets the current record's "id_profesor_materia" value
 * @method PaseDeLista     setProfesorMateria()     Sets the current record's "ProfesorMateria" value
 * 
 * @package    escuela
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePaseDeLista extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pase_de_lista');
        $this->hasColumn('id_pase_de_lista', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_profesor_materia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProfesorMateria', array(
             'local' => 'id_profesor_materia',
             'foreign' => 'id_profesor_materia'));
    }
}