<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AlumnoProfesorMateria', 'doctrine');

/**
 * BaseAlumnoProfesorMateria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_alumno_profesor_materia
 * @property float $examen_semestral
 * @property string $observaciones
 * @property integer $profesor_materiaid_profesor_materia
 * @property string $alumnomatricula
 * @property Alumno $Alumno
 * @property ProfesorMateria $ProfesorMateria
 * @property Doctrine_Collection $Calificacion
 * @property Doctrine_Collection $RegFaltas
 * @property Doctrine_Collection $RegTareasNoRealizadas
 * 
 * @method integer               getIdAlumnoProfesorMateria()             Returns the current record's "id_alumno_profesor_materia" value
 * @method float                 getExamenSemestral()                     Returns the current record's "examen_semestral" value
 * @method string                getObservaciones()                       Returns the current record's "observaciones" value
 * @method integer               getProfesorMateriaidProfesorMateria()    Returns the current record's "profesor_materiaid_profesor_materia" value
 * @method string                getAlumnomatricula()                     Returns the current record's "alumnomatricula" value
 * @method Alumno                getAlumno()                              Returns the current record's "Alumno" value
 * @method ProfesorMateria       getProfesorMateria()                     Returns the current record's "ProfesorMateria" value
 * @method Doctrine_Collection   getCalificacion()                        Returns the current record's "Calificacion" collection
 * @method Doctrine_Collection   getRegFaltas()                           Returns the current record's "RegFaltas" collection
 * @method Doctrine_Collection   getRegTareasNoRealizadas()               Returns the current record's "RegTareasNoRealizadas" collection
 * @method AlumnoProfesorMateria setIdAlumnoProfesorMateria()             Sets the current record's "id_alumno_profesor_materia" value
 * @method AlumnoProfesorMateria setExamenSemestral()                     Sets the current record's "examen_semestral" value
 * @method AlumnoProfesorMateria setObservaciones()                       Sets the current record's "observaciones" value
 * @method AlumnoProfesorMateria setProfesorMateriaidProfesorMateria()    Sets the current record's "profesor_materiaid_profesor_materia" value
 * @method AlumnoProfesorMateria setAlumnomatricula()                     Sets the current record's "alumnomatricula" value
 * @method AlumnoProfesorMateria setAlumno()                              Sets the current record's "Alumno" value
 * @method AlumnoProfesorMateria setProfesorMateria()                     Sets the current record's "ProfesorMateria" value
 * @method AlumnoProfesorMateria setCalificacion()                        Sets the current record's "Calificacion" collection
 * @method AlumnoProfesorMateria setRegFaltas()                           Sets the current record's "RegFaltas" collection
 * @method AlumnoProfesorMateria setRegTareasNoRealizadas()               Sets the current record's "RegTareasNoRealizadas" collection
 * 
 * @package    escuela
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlumnoProfesorMateria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('alumno_profesor_materia');
        $this->hasColumn('id_alumno_profesor_materia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('examen_semestral', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('observaciones', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('profesor_materiaid_profesor_materia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('alumnomatricula', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Alumno', array(
             'local' => 'alumnomatricula',
             'foreign' => 'matricula'));

        $this->hasOne('ProfesorMateria', array(
             'local' => 'profesor_materiaid_profesor_materia',
             'foreign' => 'id_profesor_materia'));

        $this->hasMany('Calificacion', array(
             'local' => 'id_alumno_profesor_materia',
             'foreign' => 'alumno_profesor_materiaid_alumno_profesor_materia'));

        $this->hasMany('RegFaltas', array(
             'local' => 'id_alumno_profesor_materia',
             'foreign' => 'alumno_profesor_materiaid_alumno_profesor_materia'));

        $this->hasMany('RegTareasNoRealizadas', array(
             'local' => 'id_alumno_profesor_materia',
             'foreign' => 'alumno_profesor_materiaid_alumno_profesor_materia'));
    }
}