<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/09/06 17:01:08

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=escuela',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
