Alumno:
  connection: doctrine
  tableName: alumno
  columns:
    matricula:
      type: string(20)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    nombre:
      type: string(80)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ap_paterno:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ap_materno:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    estatus:
      type: string(6)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    id_grupo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Grupo:
      local: id_grupo
      foreign: id_grupo
      type: one
    AlumnoProfesorMateria:
      local: matricula
      foreign: alumnomatricula
      type: many
AlumnoProfesorMateria:
  connection: doctrine
  tableName: alumno_profesor_materia
  columns:
    id_alumno_profesor_materia:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    examen_semestral:
      type: float(18)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    observaciones:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    profesor_materiaid_profesor_materia:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    alumnomatricula:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Alumno:
      local: alumnomatricula
      foreign: matricula
      type: one
    ProfesorMateria:
      local: profesor_materiaid_profesor_materia
      foreign: id_profesor_materia
      type: one
    Calificacion:
      local: id_alumno_profesor_materia
      foreign: alumno_profesor_materiaid_alumno_profesor_materia
      type: many
    RegFaltas:
      local: id_alumno_profesor_materia
      foreign: alumno_profesor_materiaid_alumno_profesor_materia
      type: many
    RegTareasNoRealizadas:
      local: id_alumno_profesor_materia
      foreign: alumno_profesor_materiaid_alumno_profesor_materia
      type: many
Calificacion:
  connection: doctrine
  tableName: calificacion
  columns:
    id_unidad:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    numero_unidad:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    clasificacion:
      type: float(18)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    tipo:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    alumno_profesor_materiaid_alumno_profesor_materia:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    AlumnoProfesorMateria:
      local: alumno_profesor_materiaid_alumno_profesor_materia
      foreign: id_alumno_profesor_materia
      type: one
Cuenta:
  connection: doctrine
  tableName: cuenta
  columns:
    id_cuenta:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    usuario:
      type: string(40)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    contrasenia:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    rolid_rol:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Rol:
      local: rolid_rol
      foreign: id_rol
      type: one
    Profesor:
      local: id_cuenta
      foreign: cuentaid_cuenta
      type: many
Grupo:
  connection: doctrine
  tableName: grupo
  columns:
    id_grupo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    semestre:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    num_grupo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Alumno:
      local: id_grupo
      foreign: id_grupo
      type: many
    ProfesorMateria:
      local: id_grupo
      foreign: grupoid_grupo
      type: many
Materia:
  connection: doctrine
  tableName: materia
  columns:
    clave:
      type: string(3)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    nombre:
      type: string(70)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    semestre:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    ProfesorMateria:
      local: clave
      foreign: materiaclave
      type: many
Profesor:
  connection: doctrine
  tableName: profesor
  columns:
    id_profesor:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ap_paterno:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ap_materno:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    cuentaid_cuenta:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Cuenta:
      local: cuentaid_cuenta
      foreign: id_cuenta
      type: one
    ProfesorMateria:
      local: id_profesor
      foreign: profesorid_profesor
      type: many
ProfesorMateria:
  connection: doctrine
  tableName: profesor_materia
  columns:
    id_profesor_materia:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    periodo:
      type: string(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    profesorid_profesor:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    materiaclave:
      type: string(3)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    grupoid_grupo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Grupo:
      local: grupoid_grupo
      foreign: id_grupo
      type: one
    Materia:
      local: materiaclave
      foreign: clave
      type: one
    Profesor:
      local: profesorid_profesor
      foreign: id_profesor
      type: one
    AlumnoProfesorMateria:
      local: id_profesor_materia
      foreign: profesor_materiaid_profesor_materia
      type: many
RegFaltas:
  connection: doctrine
  tableName: reg_faltas
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    fecha:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    num_unidad:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    alumno_profesor_materiaid_alumno_profesor_materia:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    AlumnoProfesorMateria:
      local: alumno_profesor_materiaid_alumno_profesor_materia
      foreign: id_alumno_profesor_materia
      type: one
RegTareasNoRealizadas:
  connection: doctrine
  tableName: reg_tareas_no_realizadas
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    fecha:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    descripcion:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    num_unidad:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    alumno_profesor_materiaid_alumno_profesor_materia:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    AlumnoProfesorMateria:
      local: alumno_profesor_materiaid_alumno_profesor_materia
      foreign: id_alumno_profesor_materia
      type: one
Rol:
  connection: doctrine
  tableName: rol
  columns:
    id_rol:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Cuenta:
      local: id_rol
      foreign: rolid_rol
      type: many
VariablesGlobales:
  connection: doctrine
  tableName: variables_globales
  columns:
    id_variables_globales:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    eval_fecha_inicio:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    eval_fecha_fin:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    estatus:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    unidad_actual:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    semestre_actual:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
