<?php

/**
 * Alumno
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    escuela
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Alumno extends BaseAlumno
{
    public function __toString() {
        return $this->getNombre()." ".$this->getApPaterno()." ".$this->getApMaterno();
    }
}